//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace ReserveOnWeb.ReserveOnService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataUsingDataContractOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsereClienteUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback AutenticarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback InserirMesaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AtualizarMesaOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeletarMesaOperationCompleted;
        
        private System.Threading.SendOrPostCallback InserirReservaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AtualizarReservaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExisteUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback TesteConexaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback TesteConexaoParamOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::ReserveOnWeb.Properties.Settings.Default.ReserveOnWeb_ReserveOn_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDataCompletedEventHandler GetDataCompleted;
        
        /// <remarks/>
        public event GetDataUsingDataContractCompletedEventHandler GetDataUsingDataContractCompleted;
        
        /// <remarks/>
        public event InsereClienteUsuarioCompletedEventHandler InsereClienteUsuarioCompleted;
        
        /// <remarks/>
        public event AutenticarUsuarioCompletedEventHandler AutenticarUsuarioCompleted;
        
        /// <remarks/>
        public event InserirMesaCompletedEventHandler InserirMesaCompleted;
        
        /// <remarks/>
        public event AtualizarMesaCompletedEventHandler AtualizarMesaCompleted;
        
        /// <remarks/>
        public event DeletarMesaCompletedEventHandler DeletarMesaCompleted;
        
        /// <remarks/>
        public event InserirReservaCompletedEventHandler InserirReservaCompleted;
        
        /// <remarks/>
        public event AtualizarReservaCompletedEventHandler AtualizarReservaCompleted;
        
        /// <remarks/>
        public event ExisteUsuarioCompletedEventHandler ExisteUsuarioCompleted;
        
        /// <remarks/>
        public event TesteConexaoCompletedEventHandler TesteConexaoCompleted;
        
        /// <remarks/>
        public event TesteConexaoParamCompletedEventHandler TesteConexaoParamCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/GetData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetData(int value, [System.Xml.Serialization.XmlIgnoreAttribute()] bool valueSpecified) {
            object[] results = this.Invoke("GetData", new object[] {
                        value,
                        valueSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataAsync(int value, bool valueSpecified) {
            this.GetDataAsync(value, valueSpecified, null);
        }
        
        /// <remarks/>
        public void GetDataAsync(int value, bool valueSpecified, object userState) {
            if ((this.GetDataOperationCompleted == null)) {
                this.GetDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataOperationCompleted);
            }
            this.InvokeAsync("GetData", new object[] {
                        value,
                        valueSpecified}, this.GetDataOperationCompleted, userState);
        }
        
        private void OnGetDataOperationCompleted(object arg) {
            if ((this.GetDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/GetDataUsingDataContract", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CompositeType GetDataUsingDataContract([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] CompositeType composite) {
            object[] results = this.Invoke("GetDataUsingDataContract", new object[] {
                        composite});
            return ((CompositeType)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataUsingDataContractAsync(CompositeType composite) {
            this.GetDataUsingDataContractAsync(composite, null);
        }
        
        /// <remarks/>
        public void GetDataUsingDataContractAsync(CompositeType composite, object userState) {
            if ((this.GetDataUsingDataContractOperationCompleted == null)) {
                this.GetDataUsingDataContractOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataUsingDataContractOperationCompleted);
            }
            this.InvokeAsync("GetDataUsingDataContract", new object[] {
                        composite}, this.GetDataUsingDataContractOperationCompleted, userState);
        }
        
        private void OnGetDataUsingDataContractOperationCompleted(object arg) {
            if ((this.GetDataUsingDataContractCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataUsingDataContractCompleted(this, new GetDataUsingDataContractCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InsereClienteUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InsereClienteUsuario([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] PessoaEntity Cliente, out bool InsereClienteUsuarioResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool InsereClienteUsuarioResultSpecified) {
            object[] results = this.Invoke("InsereClienteUsuario", new object[] {
                        Cliente});
            InsereClienteUsuarioResult = ((bool)(results[0]));
            InsereClienteUsuarioResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void InsereClienteUsuarioAsync(PessoaEntity Cliente) {
            this.InsereClienteUsuarioAsync(Cliente, null);
        }
        
        /// <remarks/>
        public void InsereClienteUsuarioAsync(PessoaEntity Cliente, object userState) {
            if ((this.InsereClienteUsuarioOperationCompleted == null)) {
                this.InsereClienteUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsereClienteUsuarioOperationCompleted);
            }
            this.InvokeAsync("InsereClienteUsuario", new object[] {
                        Cliente}, this.InsereClienteUsuarioOperationCompleted, userState);
        }
        
        private void OnInsereClienteUsuarioOperationCompleted(object arg) {
            if ((this.InsereClienteUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsereClienteUsuarioCompleted(this, new InsereClienteUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AutenticarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PessoaEntity AutenticarUsuario([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] UsuarioEntity Usuario) {
            object[] results = this.Invoke("AutenticarUsuario", new object[] {
                        Usuario});
            return ((PessoaEntity)(results[0]));
        }
        
        /// <remarks/>
        public void AutenticarUsuarioAsync(UsuarioEntity Usuario) {
            this.AutenticarUsuarioAsync(Usuario, null);
        }
        
        /// <remarks/>
        public void AutenticarUsuarioAsync(UsuarioEntity Usuario, object userState) {
            if ((this.AutenticarUsuarioOperationCompleted == null)) {
                this.AutenticarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAutenticarUsuarioOperationCompleted);
            }
            this.InvokeAsync("AutenticarUsuario", new object[] {
                        Usuario}, this.AutenticarUsuarioOperationCompleted, userState);
        }
        
        private void OnAutenticarUsuarioOperationCompleted(object arg) {
            if ((this.AutenticarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AutenticarUsuarioCompleted(this, new AutenticarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InserirMesa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InserirMesa([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] MesaEntity Mesa, out int InserirMesaResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool InserirMesaResultSpecified) {
            object[] results = this.Invoke("InserirMesa", new object[] {
                        Mesa});
            InserirMesaResult = ((int)(results[0]));
            InserirMesaResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void InserirMesaAsync(MesaEntity Mesa) {
            this.InserirMesaAsync(Mesa, null);
        }
        
        /// <remarks/>
        public void InserirMesaAsync(MesaEntity Mesa, object userState) {
            if ((this.InserirMesaOperationCompleted == null)) {
                this.InserirMesaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInserirMesaOperationCompleted);
            }
            this.InvokeAsync("InserirMesa", new object[] {
                        Mesa}, this.InserirMesaOperationCompleted, userState);
        }
        
        private void OnInserirMesaOperationCompleted(object arg) {
            if ((this.InserirMesaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InserirMesaCompleted(this, new InserirMesaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AtualizarMesa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AtualizarMesa([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] MesaEntity Mesa, out bool AtualizarMesaResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool AtualizarMesaResultSpecified) {
            object[] results = this.Invoke("AtualizarMesa", new object[] {
                        Mesa});
            AtualizarMesaResult = ((bool)(results[0]));
            AtualizarMesaResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void AtualizarMesaAsync(MesaEntity Mesa) {
            this.AtualizarMesaAsync(Mesa, null);
        }
        
        /// <remarks/>
        public void AtualizarMesaAsync(MesaEntity Mesa, object userState) {
            if ((this.AtualizarMesaOperationCompleted == null)) {
                this.AtualizarMesaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAtualizarMesaOperationCompleted);
            }
            this.InvokeAsync("AtualizarMesa", new object[] {
                        Mesa}, this.AtualizarMesaOperationCompleted, userState);
        }
        
        private void OnAtualizarMesaOperationCompleted(object arg) {
            if ((this.AtualizarMesaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AtualizarMesaCompleted(this, new AtualizarMesaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/DeletarMesa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeletarMesa([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] MesaEntity Mesa, out bool DeletarMesaResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool DeletarMesaResultSpecified) {
            object[] results = this.Invoke("DeletarMesa", new object[] {
                        Mesa});
            DeletarMesaResult = ((bool)(results[0]));
            DeletarMesaResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void DeletarMesaAsync(MesaEntity Mesa) {
            this.DeletarMesaAsync(Mesa, null);
        }
        
        /// <remarks/>
        public void DeletarMesaAsync(MesaEntity Mesa, object userState) {
            if ((this.DeletarMesaOperationCompleted == null)) {
                this.DeletarMesaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeletarMesaOperationCompleted);
            }
            this.InvokeAsync("DeletarMesa", new object[] {
                        Mesa}, this.DeletarMesaOperationCompleted, userState);
        }
        
        private void OnDeletarMesaOperationCompleted(object arg) {
            if ((this.DeletarMesaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeletarMesaCompleted(this, new DeletarMesaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InserirReserva", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InserirReserva([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ReservaEntity Reserva, out int InserirReservaResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool InserirReservaResultSpecified) {
            object[] results = this.Invoke("InserirReserva", new object[] {
                        Reserva});
            InserirReservaResult = ((int)(results[0]));
            InserirReservaResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void InserirReservaAsync(ReservaEntity Reserva) {
            this.InserirReservaAsync(Reserva, null);
        }
        
        /// <remarks/>
        public void InserirReservaAsync(ReservaEntity Reserva, object userState) {
            if ((this.InserirReservaOperationCompleted == null)) {
                this.InserirReservaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInserirReservaOperationCompleted);
            }
            this.InvokeAsync("InserirReserva", new object[] {
                        Reserva}, this.InserirReservaOperationCompleted, userState);
        }
        
        private void OnInserirReservaOperationCompleted(object arg) {
            if ((this.InserirReservaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InserirReservaCompleted(this, new InserirReservaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AtualizarReserva", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AtualizarReserva([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ReservaEntity Reserva, out bool AtualizarReservaResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool AtualizarReservaResultSpecified) {
            object[] results = this.Invoke("AtualizarReserva", new object[] {
                        Reserva});
            AtualizarReservaResult = ((bool)(results[0]));
            AtualizarReservaResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void AtualizarReservaAsync(ReservaEntity Reserva) {
            this.AtualizarReservaAsync(Reserva, null);
        }
        
        /// <remarks/>
        public void AtualizarReservaAsync(ReservaEntity Reserva, object userState) {
            if ((this.AtualizarReservaOperationCompleted == null)) {
                this.AtualizarReservaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAtualizarReservaOperationCompleted);
            }
            this.InvokeAsync("AtualizarReserva", new object[] {
                        Reserva}, this.AtualizarReservaOperationCompleted, userState);
        }
        
        private void OnAtualizarReservaOperationCompleted(object arg) {
            if ((this.AtualizarReservaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AtualizarReservaCompleted(this, new AtualizarReservaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ExisteUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ExisteUsuario([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] UsuarioEntity usuario, out bool ExisteUsuarioResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool ExisteUsuarioResultSpecified) {
            object[] results = this.Invoke("ExisteUsuario", new object[] {
                        usuario});
            ExisteUsuarioResult = ((bool)(results[0]));
            ExisteUsuarioResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void ExisteUsuarioAsync(UsuarioEntity usuario) {
            this.ExisteUsuarioAsync(usuario, null);
        }
        
        /// <remarks/>
        public void ExisteUsuarioAsync(UsuarioEntity usuario, object userState) {
            if ((this.ExisteUsuarioOperationCompleted == null)) {
                this.ExisteUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExisteUsuarioOperationCompleted);
            }
            this.InvokeAsync("ExisteUsuario", new object[] {
                        usuario}, this.ExisteUsuarioOperationCompleted, userState);
        }
        
        private void OnExisteUsuarioOperationCompleted(object arg) {
            if ((this.ExisteUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExisteUsuarioCompleted(this, new ExisteUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/TesteConexao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void TesteConexao(out bool TesteConexaoResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool TesteConexaoResultSpecified) {
            object[] results = this.Invoke("TesteConexao", new object[0]);
            TesteConexaoResult = ((bool)(results[0]));
            TesteConexaoResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void TesteConexaoAsync() {
            this.TesteConexaoAsync(null);
        }
        
        /// <remarks/>
        public void TesteConexaoAsync(object userState) {
            if ((this.TesteConexaoOperationCompleted == null)) {
                this.TesteConexaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTesteConexaoOperationCompleted);
            }
            this.InvokeAsync("TesteConexao", new object[0], this.TesteConexaoOperationCompleted, userState);
        }
        
        private void OnTesteConexaoOperationCompleted(object arg) {
            if ((this.TesteConexaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TesteConexaoCompleted(this, new TesteConexaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/TesteConexaoParam", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void TesteConexaoParam(int i, [System.Xml.Serialization.XmlIgnoreAttribute()] bool iSpecified, out bool TesteConexaoParamResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool TesteConexaoParamResultSpecified) {
            object[] results = this.Invoke("TesteConexaoParam", new object[] {
                        i,
                        iSpecified});
            TesteConexaoParamResult = ((bool)(results[0]));
            TesteConexaoParamResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void TesteConexaoParamAsync(int i, bool iSpecified) {
            this.TesteConexaoParamAsync(i, iSpecified, null);
        }
        
        /// <remarks/>
        public void TesteConexaoParamAsync(int i, bool iSpecified, object userState) {
            if ((this.TesteConexaoParamOperationCompleted == null)) {
                this.TesteConexaoParamOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTesteConexaoParamOperationCompleted);
            }
            this.InvokeAsync("TesteConexaoParam", new object[] {
                        i,
                        iSpecified}, this.TesteConexaoParamOperationCompleted, userState);
        }
        
        private void OnTesteConexaoParamOperationCompleted(object arg) {
            if ((this.TesteConexaoParamCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TesteConexaoParamCompleted(this, new TesteConexaoParamCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/ClickOnService")]
    public partial class CompositeType {
        
        private bool boolValueField;
        
        private bool boolValueFieldSpecified;
        
        private string stringValueField;
        
        /// <remarks/>
        public bool BoolValue {
            get {
                return this.boolValueField;
            }
            set {
                this.boolValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BoolValueSpecified {
            get {
                return this.boolValueFieldSpecified;
            }
            set {
                this.boolValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StringValue {
            get {
                return this.stringValueField;
            }
            set {
                this.stringValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    public partial class ReservaEntity {
        
        private string codigoCheckinField;
        
        private string codigoReservaField;
        
        private System.DateTime dataReservaFimField;
        
        private bool dataReservaFimFieldSpecified;
        
        private System.DateTime dataReservaInicioField;
        
        private bool dataReservaInicioFieldSpecified;
        
        private bool flagAtivaField;
        
        private bool flagAtivaFieldSpecified;
        
        private bool flagCheckinField;
        
        private bool flagCheckinFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private MesaEntity mesaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CodigoCheckin {
            get {
                return this.codigoCheckinField;
            }
            set {
                this.codigoCheckinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CodigoReserva {
            get {
                return this.codigoReservaField;
            }
            set {
                this.codigoReservaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataReservaFim {
            get {
                return this.dataReservaFimField;
            }
            set {
                this.dataReservaFimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataReservaFimSpecified {
            get {
                return this.dataReservaFimFieldSpecified;
            }
            set {
                this.dataReservaFimFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataReservaInicio {
            get {
                return this.dataReservaInicioField;
            }
            set {
                this.dataReservaInicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataReservaInicioSpecified {
            get {
                return this.dataReservaInicioFieldSpecified;
            }
            set {
                this.dataReservaInicioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool FlagAtiva {
            get {
                return this.flagAtivaField;
            }
            set {
                this.flagAtivaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FlagAtivaSpecified {
            get {
                return this.flagAtivaFieldSpecified;
            }
            set {
                this.flagAtivaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool FlagCheckin {
            get {
                return this.flagCheckinField;
            }
            set {
                this.flagCheckinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FlagCheckinSpecified {
            get {
                return this.flagCheckinFieldSpecified;
            }
            set {
                this.flagCheckinFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MesaEntity Mesa {
            get {
                return this.mesaField;
            }
            set {
                this.mesaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    public partial class MesaEntity {
        
        private string descricaoLocalizacaoField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private int qrCodeField;
        
        private bool qrCodeFieldSpecified;
        
        private int quantidadeLugaresField;
        
        private bool quantidadeLugaresFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DescricaoLocalizacao {
            get {
                return this.descricaoLocalizacaoField;
            }
            set {
                this.descricaoLocalizacaoField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int QrCode {
            get {
                return this.qrCodeField;
            }
            set {
                this.qrCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QrCodeSpecified {
            get {
                return this.qrCodeFieldSpecified;
            }
            set {
                this.qrCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int QuantidadeLugares {
            get {
                return this.quantidadeLugaresField;
            }
            set {
                this.quantidadeLugaresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantidadeLugaresSpecified {
            get {
                return this.quantidadeLugaresFieldSpecified;
            }
            set {
                this.quantidadeLugaresFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    public partial class PerfilEntity {
        
        private string descricaoField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    public partial class UsuarioEntity {
        
        private int idField;
        
        private string loginField;
        
        private PerfilEntity perfilField;
        
        private string senhaField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PerfilEntity Perfil {
            get {
                return this.perfilField;
            }
            set {
                this.perfilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    public partial class PessoaEntity {
        
        private string enderecoEmailField;
        
        private int idField;
        
        private string nomeField;
        
        private string numeroCpfField;
        
        private string numeroRgField;
        
        private string numeroTelefoneField;
        
        private UsuarioEntity usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EnderecoEmail {
            get {
                return this.enderecoEmailField;
            }
            set {
                this.enderecoEmailField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NumeroCpf {
            get {
                return this.numeroCpfField;
            }
            set {
                this.numeroCpfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NumeroRg {
            get {
                return this.numeroRgField;
            }
            set {
                this.numeroRgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NumeroTelefone {
            get {
                return this.numeroTelefoneField;
            }
            set {
                this.numeroTelefoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UsuarioEntity Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetDataCompletedEventHandler(object sender, GetDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetDataUsingDataContractCompletedEventHandler(object sender, GetDataUsingDataContractCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataUsingDataContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataUsingDataContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CompositeType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CompositeType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void InsereClienteUsuarioCompletedEventHandler(object sender, InsereClienteUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsereClienteUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsereClienteUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool InsereClienteUsuarioResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool InsereClienteUsuarioResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void AutenticarUsuarioCompletedEventHandler(object sender, AutenticarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AutenticarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AutenticarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PessoaEntity Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PessoaEntity)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void InserirMesaCompletedEventHandler(object sender, InserirMesaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InserirMesaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InserirMesaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int InserirMesaResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool InserirMesaResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void AtualizarMesaCompletedEventHandler(object sender, AtualizarMesaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AtualizarMesaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AtualizarMesaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool AtualizarMesaResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool AtualizarMesaResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DeletarMesaCompletedEventHandler(object sender, DeletarMesaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeletarMesaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeletarMesaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool DeletarMesaResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool DeletarMesaResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void InserirReservaCompletedEventHandler(object sender, InserirReservaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InserirReservaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InserirReservaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int InserirReservaResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool InserirReservaResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void AtualizarReservaCompletedEventHandler(object sender, AtualizarReservaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AtualizarReservaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AtualizarReservaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool AtualizarReservaResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool AtualizarReservaResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ExisteUsuarioCompletedEventHandler(object sender, ExisteUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExisteUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExisteUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool ExisteUsuarioResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool ExisteUsuarioResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void TesteConexaoCompletedEventHandler(object sender, TesteConexaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TesteConexaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TesteConexaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool TesteConexaoResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool TesteConexaoResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void TesteConexaoParamCompletedEventHandler(object sender, TesteConexaoParamCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TesteConexaoParamCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TesteConexaoParamCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool TesteConexaoParamResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool TesteConexaoParamResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591